Import("environment")

import os
import sys

environment.Append(CPPDEFINES = "DLCL_EXPORTS=1")
result = environment.SharedLibrary("dlcl", ["dlcl_parser.cpp", "dlcl_lexer.cpp", "dlcl_std.cpp", "dlcl_utils.c"])

dlcl = [result[1], result[0]]

Return("dlcl")
